[database]
host = "kubela.id"        # Replace with your MySQL host address
port = 3306                     # Replace with your MySQL port number
user = "davis2024irwan"    # Replace with your MySQL username
password = "wh451n9m@ch1n3"    # Replace with your MySQL password
database = "aw" # Replace with your MySQL database name
